namespace WinUI3Clipper
{
    [bindable]
    [default_interface]
    runtimeclass ClipboardItem : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        ClipboardItem();
        Int32 Id;
        String Content;
        String ContentType;
        Int64 Timestamp;
        Boolean IsPinned;
        String DisplayContent{ get; };
        String FormattedTimestamp{ get; };
    }
}
